"""Phase 0 gate: empirically verify each candidate data source.

Run this FIRST. It hits each source, records exactly what came back
(status, fields, row counts, date ranges), and writes a markdown evidence
report to reports/. Nothing downstream should be trusted until this passes.

Usage:
    python -m src.verify_sources
Exit code 0 = at least one viable price+NAV path verified; 1 = none.
"""
from __future__ import annotations

import datetime as dt
import pathlib
import sys
import traceback

REPORTS = pathlib.Path(__file__).resolve().parent.parent / "reports"


def _try(label: str, fn):
    """Run a probe, capture result or the real error (incl. proxy denials)."""
    try:
        detail = fn()
        return {"probe": label, "ok": True, "detail": detail}
    except Exception as e:  # noqa: BLE001 - we want the evidence, whatever it is
        msg = f"{type(e).__name__}: {e}"
        if "403" in msg and ("proxy" in msg.lower() or "tunnel" in msg.lower()):
            msg += "  [egress policy denial - host not allowed from this environment]"
        return {"probe": label, "ok": False, "detail": msg,
                "trace": traceback.format_exc(limit=1)}


def probe_cefconnect_universe():
    from . import sources
    df = sources.fetch_cefconnect_universe()
    return (f"{len(df)} funds; columns include: "
            f"{[c for c in df.columns if c.lower() in ('ticker','name','price','nav','discount','category','volume')] or list(df.columns)[:12]}")


def probe_cefconnect_history():
    from . import sources
    df = sources.fetch_cefconnect_history("ADX", "1Y")
    return f"ADX 1Y history: {len(df)} rows; columns: {list(df.columns)[:10]}"


def probe_yahoo_price():
    from . import sources
    px = sources.fetch_yf_history("ADX", period="5y")
    if px is None:
        raise RuntimeError("no data returned for ADX")
    return f"ADX price: {len(px)} rows, {px.index.min().date()} -> {px.index.max().date()}"


def probe_yahoo_nav():
    from . import sources
    nav = sources.fetch_yf_history("XADX", period="5y")
    if nav is None:
        raise RuntimeError("no data returned for XADX")
    return f"XADX NAV: {len(nav)} rows, {nav.index.min().date()} -> {nav.index.max().date()}"


def probe_yahoo_nav_coverage():
    """How many seed-universe funds have a working X-prefixed NAV series?"""
    from . import sources
    hits, misses = [], []
    sample = sources.SEED_UNIVERSE[:15]
    for t in sample:
        nav = sources.fetch_yf_history(f"X{t}", period="1y")
        (hits if nav is not None and len(nav) > 200 else misses).append(t)
    if not hits:
        raise RuntimeError(
            f"0/{len(sample)} seed funds returned a NAV series (misses: {misses}) "
            "- either the X-ticker convention is dead or the host is blocked")
    return f"NAV coverage on {len(sample)} seed funds: {len(hits)} ok {hits}, missing {misses}"


def probe_nasdaq_data_link():
    """CEFData via Nasdaq Data Link: only checks reachability + auth model.
    Content verification requires an API key (paid product; free sample)."""
    import requests
    r = requests.get("https://data.nasdaq.com/api/v3/datatables/", timeout=30)
    return f"data.nasdaq.com reachable, HTTP {r.status_code} (API key still required for CEF tables)"


PROBES = [
    ("CEFConnect universe (api/v3/DailyPricing)", probe_cefconnect_universe),
    ("CEFConnect fund history (api/v3/pricinghistory ADX)", probe_cefconnect_history),
    ("Yahoo price history (ADX via yfinance)", probe_yahoo_price),
    ("Yahoo NAV pseudo-ticker (XADX via yfinance)", probe_yahoo_nav),
    ("Yahoo NAV coverage across 15 seed funds", probe_yahoo_nav_coverage),
    ("Nasdaq Data Link reachability (paid CEFData feed)", probe_nasdaq_data_link),
]


def main() -> int:
    results = [_try(label, fn) for label, fn in PROBES]

    today = dt.date.today().isoformat()
    lines = [
        f"# Data source verification — {today}",
        "",
        "Machine-generated by `python -m src.verify_sources`. Every line is the",
        "actual response observed at run time; nothing here is assumed.",
        "",
    ]
    for r in results:
        badge = "PASS" if r["ok"] else "FAIL"
        lines += [f"## [{badge}] {r['probe']}", "", f"    {r['detail']}", ""]

    # Verdict: viable iff both Yahoo probes (price + NAV) pass, since that
    # pair is the deep-history path; CEFConnect alone has shallow history.
    yahoo_ok = all(r["ok"] for r in results if r["probe"].startswith("Yahoo price")
                   or r["probe"].startswith("Yahoo NAV pseudo"))
    lines += ["## Verdict", ""]
    if yahoo_ok:
        lines += ["Price+NAV path VERIFIED (Yahoo). Proceed to `python -m src.build_dataset`.", ""]
    else:
        lines += ["NO viable price+NAV path from this environment. Do NOT proceed",
                  "to dataset build or backtest; fix network access first.", ""]

    REPORTS.mkdir(parents=True, exist_ok=True)
    out = REPORTS / f"source_verification_{today}.md"
    out.write_text("\n".join(lines))
    print("\n".join(lines))
    print(f"[written] {out}")
    return 0 if yahoo_ok else 1


if __name__ == "__main__":
    sys.exit(main())
